### ISSUE TITLE
when open source code

### ISSUE THREAD

**Issue by you-old** [zhangyp15/BEVerse#1]
hi dalao:
    thank you for great work, when open source code?

**Comment by menglongyue** [comment]
+1

**Comment by sgzqc** [comment]
+1

**Comment by abhigoku10** [comment]
@you-old  when shall be the code released !!!!

**Comment by SongTianCai** [comment]
thank you for great work, when open source code?

**Comment by gsg213** [comment]
+1

**Comment by duohaoxue** [comment]
+1

**Comment by zhangyp15** [comment]
Thanks for your attention and the code has been released.
