### ISSUE TITLE
Dear author, how to generate the motion gt labels of the nuscenes dataset ? thanks a lot.

### ISSUE THREAD

**Issue by emilyemliyM** [zhangyp15/BEVerse#4]

**Comment by zhangyp15** [comment]
We use the code from [FIERY](https://github.com/wayveai/fiery) to generate the motion labels. 

Also, the generation of motion labels is implemented with the function  **ConvertMotionLabels** during the **train_pipeline**. Check the function at projects/mmdet3d_plugin/datasets/pipelines/motion_labels.py
