### ISSUE TITLE
raw data for training

### ISSUE THREAD

**Issue by jian-6666** [zhangyp15/BEVerse#7]
Hi, thanks for your great work! I am very impressed! if you do not mind, could I ask, during trainining , i would like to use the raw nuscenes data, not to use data augmentation, could I turn down data augmentation, if so, how and where could I deal with it~

Looking forward to your reply~

**Comment by zhangyp15** [comment]
You need to change the train_pipeline in the config file. 

To disable the img augmentation, a simple way is to set "is_train" as False for the function LoadMultiViewImageFromFiles_MTL. To disable the bev augmentation, remove the MTLGlobalRotScaleTrans and MTLRandomFlip3D.

Try this config: [beverse_singleframe_tiny_raw.zip](https://github.com/zhangyp15/BEVerse/files/9316462/beverse_singleframe_tiny_raw.zip)

**Comment by jian-6666** [comment]
thanks for your reply, that is very kind of you, I am really appreciate it ! 
For the config file, I use your config file, "beverse_singeframe_tiny_raw.py", I saw you change the "is train" to  "False", and you also remove the 2 blocks of train pipeline, but when I use this file for training, the number of trianing data is 123580, six times as the raw nuscenes data(seems also used img augmentation). Do you have any idea why it appear like this?
Looking forward to your reply~
