### ISSUE TITLE
How to remove the data dependency of 3d detection and future prediction task if I only need to train the semantic map branch based on my custom dataset?

### ISSUE THREAD

**Issue by alanlyawen** [zhangyp15/BEVerse#9]
Thanks for your great work the and open source code！I would to ask you for some help about remove the  trainning and eval data dependency of 3d detection and future prediction task  branch in your codebase. In this way I can only train the the semantic map branch on custom datasets. Thank you again！

**Comment by zhangyp15** [comment]
Hi, thanks for your attention. 

To only train the semantic map and get better single-task performance, please check the following items in the config file:

1. Change the key "task_enbale" in the pts_bbox_head and set the unwanted tasks as False. 
2. The default grid_conf with 0.8m interval (follows the det_grid_conf) is a little coarse, you can use the map_grid_conf as the default grids to get better performance.

Feel free to ask if you meet other problems.

**Comment by alanlyawen** [comment]
Thanks for your help!

**Comment by lilyzhng** [comment]
@zhangyp15 Dear author, I would like to train the detection only task. Could you share your recommendation on preparing the config file?
